import React from 'react';
import Head from 'next/head'
import Background from 'comps/Background';

import Image from 'next/image'
import { useMediaQuery } from 'react-responsive';

export default function Home() {

  const isLaptop = useMediaQuery({query: '(min-width: 1224px)'})
  const isLaptopDevice = useMediaQuery({query: '(max-width: 1640px)'})
    const isDesktop = useMediaQuery({ query: '(min-device-width: 1641px)' })
    const isTabletOrMobile = useMediaQuery({ query: '(max-width: 1224px)' })
    const isTabletOrMobileDevice = useMediaQuery({query: '(max-device-width: 1223px)'})
    const isPortrait = useMediaQuery({ query: '(orientation: portrait)' })
    const isRetina = useMediaQuery({ query: '(min-resolution: 2dppx)' })

  return ( <div className="page">
      <Head>
        <title>YH Zhang | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <button className="start" >click</button> */}
      <Background open={true}/>
      {/* {isLaptop && <Image src="/laptop.svg" layout="fill"/>}
      {isTabletOrMobile &&  <Image src="/vertical.svg" layout="fill"/>} */}
    </div>
  )
}
